repositories:
  - url: "https://grafana.github.io/helm-charts"
    charts:
      - grafana
  - url: "https://prometheus-community.github.io/helm-charts"
    charts:
      - prometheus
  - url: "https://charts.bitnami.com/bitnami"
    charts:
      - external-dns
  - url: "https://charts.external-secrets.io"
    charts:
      - external-secrets
